### ISSUE TITLE
Add "format" facet

### ISSUE THREAD

**Issue by fsampson** [ibm-cds-labs/devcenter#17]
Add a "format" facet to indicate the document's format (as opposed to document type).
Initial values:

- HTML
- PDF
- Podcast
- Video
- Webcast

**Comment by wswtizer** [comment]
Hi @glynnbird , Would we be able to get this new facet asap? The changes are being implemented for the content cards in DSX in the next week and this is a field we need to display. Thanks!

**Comment by glynnbird** [comment]
done
