### ISSUE TITLE
Please delete Machine Learning for Designers https://www.oreilly.com/learning/machine-learning-for-designers

### ISSUE THREAD

**Issue by wswtizer** [ibm-cds-labs/devcenter#19]
Hi,

I can't modify or delete the following item:
Machine Learning for Designers
https://www.oreilly.com/learning/machine-learning-for-designers

Can you please move it to deleted status?

Thanks.

**Comment by mikebroberg** [comment]
Yeah @glynnbird or @vabarbosa I can't delete this provisional document either.

**Comment by glynnbird** [comment]
looking @mikebroberg

**Comment by glynnbird** [comment]
deleted
