### ISSUE TITLE
Taxonomy value additions and changes

### ISSUE THREAD

**Issue by wswtizer** [ibm-cds-labs/devcenter#30]
Could you please make the following changes? Thanks

Languages:
- [ ] change BigSQL to Big SQL

Technologies:
add
- [ ] Brunel
- [ ] Object Storage
- [ ] Pandas

Topic:
add
- [ ] Communication
- [ ] Data Exploration
- [ ] Deep Learning
- [ ] Finance
- [ ] Geospatial Analytics
- [ ] Neural Networks
- [ ] Packages
- [ ] Probabilities
- [ ] Theory
- [ ] Time Series
- [ ] Use Case

**Comment by jessmantaro** [comment]
Please DO NOT remove **Webcast**. DevAdvocacy uses this tag for our demo videos. Thanks.  Also, is it really necessary to add another "Tutorial" entry for DSX, when there's already a tutorial entry and a separate field for the DSX space.  Just trying to keep the meta data to a minimum....   Thanks!

**Comment by jessmantaro** [comment]
Also, perhaps we should discuss **Geospatial** vs. **Location**. Having both may split traffic and unintentionally hide articles/content. Thoughts?

**Comment by wswtizer** [comment]
Hi @jessmantaro , sorry about that. The Format field was one that we had added, so I didn't think that the other teams were using it. 

Let me get back to you on the other comments.

**Comment by wswtizer** [comment]
I've modified the original list as per comments above.

**Comment by glynnbird** [comment]
Done
